version: '3.8'

services:
  backend:
    container_name: neighbourly-backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    volumes:
      - ./apps/backend/data:/app/apps/backend/data
    ports:
      - '5000:5000'

  frontend:
    container_name: neighbourly-frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - '8080:8080'

  database:
    container_name: neighbourly_database
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=neighbourly
    volumes:
      - ./data:/var/lib/postgresql/data
