version: '3.8'

services:
  database:
    container_name: neighbourly_database
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=neighbourly
    volumes:
      - ./data:/var/lib/postgresql/data
